name: fidelyz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  avatar_glow: ^2.0.2
  pinput: ^3.0.1
  badges: ^3.1.2
  pretty_qr_code: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_swipe_button: ^2.1.1+1
  fluttertoast: ^8.2.2
  image_picker: ^1.0.4
  expandable_page_view: ^1.0.17
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  flutter_image_compress: ^1.0.0
  image: ^4.1.3
  http: ^1.1.2
  get: ^4.6.6
  carousel_slider: ^4.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter_google_maps_webservices: ^1.1.1
  dotted_border: ^2.1.0
  geocoding: ^2.1.1
  shimmer: ^3.0.0
  custom_info_window: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/logo/
    - assets/social/
    - assets/vectors/
    - assets/onboarding/
    - assets/icons/
    - assets/image/
    - assets/shop-icon/
    - assets/dummy-image/
    - assets/category-icon/
    - assets/shops/
    - assets/profile/
    - assets/new_update/
    - assets/search_screen/
    - assets/qr code/


  fonts:
    - family: Comforta
      fonts:
        - asset: fonts/Comfortaa-VariableFont_wght.ttf
    - family: Comfortaa-Medium
      fonts:
        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500
    - family: Comfortaa-SemiBold
      fonts:
        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 700
    - family: Comfortaa-Bold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 900
    - family: Comfortaa-Light
      fonts:
        - asset: fonts/Comfortaa-Light.ttf